name: mysophobia_io
description: nCov-SARS-2 Tracker.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pull_to_refresh: ^1.6.1
  flutter_spinkit: ^4.1.2+1
  auto_route: 0.6.7
  freezed_annotation: 0.11.0+1
  flutter_bloc: 6.0.1
  equatable: ^1.2.3
  dartz: 0.9.1
  data_connection_checker: 0.3.4
  dio: ^3.0.10    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.6.8
  freezed: ^0.11.5

flutter:
  uses-material-design: true
